# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
