# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red_nodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'verbose_name_plural': 'Columnas de la tabla de indicadores de red'},
        ),
    ]
