# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_nodos', '0003_auto_20170609_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ('order',), 'verbose_name_plural': 'Columnas de la tabla de indicadores de red'},
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
