sudo: required
dist: trusty

addons:
  apt:
    packages:
    - net-tools
    - openvpn

services:
- docker

language: python
python:
- "3.6"

env:
- DJANGO_SETTINGS_MODULE=conf.settings.testing NODE_JS_VERSION=v8.11.2

before_install:
- sudo service postgresql stop
- docker-compose pull
- docker-compose up -d redis
- docker-compose ps

install:
- pip install -r requirements/testing.txt
- nvm install $NODE_JS_VERSION
- nvm use $NODE_JS_VERSION
- npm install

script:
- scripts/eslint.sh
- scripts/pep8.sh
- scripts/jscpd.sh
- scripts/pylint.sh
- scripts/tests.sh

#deploy:
#  - skip_cleanup: true
#    provider: script
#    script: scripts/deploy/run_deploy.sh testing
#    on:
#      branch: master
