site_name: Monitoreo Apertura
site_url: https://datosgobar.github.io/monitoreo-apertura
site_description: Documentación de la aplicación web de monitoreo y operación de la red de nodos de datos abiertos de la Administración Pública Nacional de la República Argentina.
site_author: Datos Argentina
repo_url: https://github.com/datosgobar/monitoreo-apertura/

nav:
  - Inicio: 'index.md'
  - Arquitectura: 'arquitectura.md'
  - Usuarios:
    - Comenzar a usar Monitoreo Apertura: 'quick-start.md'
    - Manual de uso: 'usage.md'
  - Desarrolladores:
    - Instalación: 'developers/install.md'
    - Actualización: 'developers/update.md'
    - Desarrollo: 'developers/development.md'
    - Tests: 'developers/tests.md'
  - Historial de versiones: HISTORY.md

theme: datosgobar_docs

markdown_extensions: [fenced_code, codehilite, admonition]

google_analytics: ['UA-91435482-1', "https://datosgobar.github.io/monitoreo-apertura"]
