---

- import_playbook: api_cluster.yml

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - basic_server
    - { role: maintenance, maintenance_on: yes }
    - postgresql
    - redis

- hosts: all
  become: yes
  become_method: sudo
  become_user: "{{ application_user }}"
  roles:
    - django_application

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - web_server
    - { role: maintenance, maintenance_off: yes }


