# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorRed',
            fields=[
                ('indicador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Indicador')),
            ],
            bases=('dashboard.indicador',),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='indicador_valor',
            field=models.CharField(max_length=300),
        ),
    ]
