# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170526_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='indicadorred',
            options={'verbose_name_plural': 'Indicadores de red'},
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fecha',
            field=models.DateField(),
        ),
    ]
