# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170606_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicadorRed',
        ),
    ]
