# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170608_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorRed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('indicador_nombre', models.CharField(max_length=100)),
                ('indicador_valor', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Indicadores de red',
            },
        ),
    ]
