# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170609_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='indicador_nombre',
            new_name='indicador_tipo',
        ),
    ]
