# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170609_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadorred',
            name='indicador_nombre',
        ),
        migrations.AddField(
            model_name='indicadorred',
            name='indicador_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.IndicatorType'),
            preserve_default=False,
        ),
    ]
