# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170704_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorRedPAD',
            fields=[
                ('indicadorred_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.IndicadorRed')),
            ],
            bases=('dashboard.indicadorred',),
        ),
        migrations.RenameField(
            model_name='indicador',
            old_name='catalogo_nombre',
            new_name='jurisdiccion_nombre',
        ),
        migrations.RemoveField(
            model_name='indicadorpad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='indicadorpad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indicadorpad',
            name='indicador_tipo',
        ),
        migrations.RemoveField(
            model_name='indicadorpad',
            name='indicador_valor',
        ),
        migrations.AddField(
            model_name='indicadorpad',
            name='indicador_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.Indicador'),
            preserve_default=False,
        ),
    ]
