# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20170706_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='indicador_valor',
            field=models.CharField(max_length=2000),
        ),
    ]
