# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170706_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadorred',
            options={'get_latest_by': 'fecha', 'verbose_name_plural': 'Indicadores agregados'},
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.IndicatorType', unique=True),
        ),
    ]
