# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170714_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='indicador_valor',
            field=models.TextField(),
        ),
    ]
