# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170803_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
