# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170803_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='full_name',
            field=models.CharField(blank=True, help_text='Usa un valor por defecto si no se especifica', max_length=100),
        ),
    ]
