# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20170814_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('apikey', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
