# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_indicatorsgenerationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicadorred',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
