# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180628_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingnode',
            name='url',
            field=models.URLField(help_text='URL del nodo federador ej: http://datos.gob.ar'),
        ),
    ]
