# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20180704_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='jurisdiccion_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
