# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 13:01
from __future__ import unicode_literals

from django.db import migrations

title_to_id_map = {
    'Datos abiertos de cultura': 'cultura',
    'Datos de la Agencia de Acceso a la Información Pública': 'aaip',
    'Datos MSAL': 'salud',
    'Datos Ministerio de Salud de la Nación': 'salud'
}


def fill_indicators_id(apps, schema_editor):
    Indicador = apps.get_model("dashboard", "Indicador")
    for title, identifier in title_to_id_map.items():
        Indicador.objects.filter(jurisdiccion_nombre=title).update(jurisdiccion_id=identifier)
        print(u"Migrados los indicadores de {}".format(identifier))


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('dashboard', '0028_populate_indicador_jurisdiccion_id'),
    ]

    operations = [
        migrations.RunPython(fill_indicators_id, migrations.RunPython.noop),
    ]
