# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models


def set_order(apps, _):
    order_counter = 0
    IndicatorType = apps.get_model("dashboard", "IndicatorType")
    ind_types = IndicatorType.objects.all()
    for ind_type in ind_types:
        ind_type.order = order_counter
        ind_type.save()
        order_counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_populate_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'ordering': ('order',), 'verbose_name_plural': 'Tipos de indicadores'},
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, null=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='resumen',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='indicatortype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, null=False, editable=False),
            preserve_default=False,
        ),
    ]
