# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 13:13
from __future__ import unicode_literals

from django.db import migrations


def close_federation_tasks(apps, schema_editor):
    FederationTask = apps.get_model("dashboard", "FederationTask")
    FederationTask.objects.all().update(status='FINISHED')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180801_1554'),
    ]

    operations = [
        migrations.RunPython(close_federation_tasks, migrations.RunPython.noop),
    ]
