# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 19:03
from __future__ import unicode_literals

from django.db import migrations


def delete_duplicated_indicators(apps, schema_editor):
    try:
        IndicadorRed = apps.get_model("dashboard", "IndicadorRed")
        delete_duplicates(IndicadorRed, ['fecha', 'indicador_tipo'])

        Indicador = apps.get_model("dashboard", "Indicador")
        delete_duplicates(Indicador, ['fecha', 'indicador_tipo', 'jurisdiccion_nombre', 'jurisdiccion_id'])

    except NotImplementedError:
        # Requiere un backend que implemente distinct()
        pass


def delete_duplicates(model, distinct_fields):
    distinct = model.objects.all().distinct(*distinct_fields).values_list('pk', flat=True)
    duplicates = model.objects.all().exclude(pk__in=distinct)
    duplicates.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20180824_1013'),
    ]

    operations = [
        migrations.RunPython(delete_duplicated_indicators, migrations.RunPython.noop)
    ]
