# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20180824_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicatorsgenerationtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportgenerationtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
