# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20181011_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationReportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando cat\xe1logos'), ('FINISHED', 'Finalizada')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Reportes de Validaci\xf3n',
            },
        ),
        migrations.AlterModelOptions(
            name='reportgenerationtask',
            options={'verbose_name_plural': 'Env\xedo de Reportes'},
        ),
    ]
