# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20181108_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortype',
            name='series',
            field=models.BooleanField(default=True),
        ),
    ]
