# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_indicatortype_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatortype',
            old_name='series',
            new_name='series_nodos',
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='series_red',
            field=models.BooleanField(default=True),
        ),
    ]
