# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_indicadorfederador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortype',
            name='series_indexadores',
            field=models.BooleanField(default=True),
        ),
    ]
