# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_harvestingnode_catalog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.HarvestingNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
