# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20190218_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatortype',
            old_name='series_indexadores',
            new_name='series_federadores',
        ),
    ]
