# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 18:44
from __future__ import unicode_literals

import json
import logging

from django.db import migrations
from pydatajson.helpers import fields_to_uppercase

LOGGER = logging.getLogger(__name__)


def normalize_values(apps, model):
    queryset = model.objects.filter(indicador_tipo__nombre__in=[
       'distribuciones_formatos_cant', 'datasets_frecuencia_cant'])

    for indicator in queryset:
        try:
            value = json.loads(indicator.indicador_valor)
            if isinstance(value, dict):
                normalized_value = fields_to_uppercase(value)
                if normalized_value != value:
                    # No quiero hacer un save si los valores no cambian
                    indicator.indicador_valor = json.dumps(normalized_value)
                    indicator.save()
        except json.JSONDecodeError:
            msg = f'error parseando el indicador:{indicator.pk}'
            LOGGER.warning(msg)


def normalize_node_indicator_values(apps, _schema_editor):
    Indicador = apps.get_model('dashboard', 'Indicador')
    normalize_values(apps, Indicador)


def normalize_network_indicator_values(apps, _schema_editor):
    IndicadorRed = apps.get_model('dashboard', 'IndicadorRed')
    normalize_values(apps, IndicadorRed)


def normalize_federator_indicator_values(apps, _schema_editor):
    IndicadorFederador = apps.get_model('dashboard', 'IndicadorFederador')
    normalize_values(apps, IndicadorFederador)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_harvestingnode_timezone'),
    ]

    operations = [
        migrations.RunPython(normalize_node_indicator_values,
                             migrations.RunPython.noop),
        migrations.RunPython(normalize_network_indicator_values,
                             migrations.RunPython.noop),
        migrations.RunPython(normalize_federator_indicator_values,
                             migrations.RunPython.noop),
    ]
