# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_harvestingnode_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField(default=1800)),
            ],
            options={
                'verbose_name': 'Configuración de corrida de generación de indicadores',
            },
        ),
    ]
