# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_harvestingnode_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksTimeouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicators_timeout', models.IntegerField(default=1800, help_text='En segundos.')),
                ('validation_timeout', models.IntegerField(default=1800, help_text='En segundos.')),
            ],
            options={
                'verbose_name': 'Timeouts de tareas',
            },
        ),
    ]
