# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_normalize_indicator_values'),
        ('dashboard', '0048_taskstimeouts'),
    ]

    operations = [
    ]
