# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0019_auto_20191021_1245'),
        ('dashboard', '0051_indicatorsvalidationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetPresentRecord',
            fields=[
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_datajsonar.Dataset', verbose_name='Dataset')),
                ('present_record', models.BooleanField(default=False, verbose_name='Presente en la última corrida de datasets no presentes')),
            ],
            options={
                'verbose_name_plural': 'Campos de presentismo de Dataset',
            },
        ),
        migrations.CreateModel(
            name='NotPresentReportGenerationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField()),
                ('node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node')),
            ],
            options={
                'verbose_name_plural': 'Reportes de datasets no presentes',
            },
        ),
    ]
