# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_indicatorsvalidationconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorsValidationConfig',
        ),
        migrations.DeleteModel(
            name='TasksTimeouts',
        ),
        migrations.AlterModelOptions(
            name='tasksconfig',
            options={'verbose_name': 'Configuracion general'},
        ),
        migrations.RemoveField(
            model_name='tasksconfig',
            name='validate_urls',
        ),
        migrations.AddField(
            model_name='tasksconfig',
            name='federation_url_check',
            field=models.BooleanField(default=True, verbose_name='Activar validación de URLs con errores de descarga en la federación'),
        ),
        migrations.AddField(
            model_name='tasksconfig',
            name='indicators_timeout',
            field=models.IntegerField(default=1800, help_text='En segundos.'),
        ),
        migrations.AddField(
            model_name='tasksconfig',
            name='indicators_url_check',
            field=models.BooleanField(default=True, verbose_name='Activar generación de indicadores de URLs con errores de descarga'),
        ),
        migrations.AddField(
            model_name='tasksconfig',
            name='validation_timeout',
            field=models.IntegerField(default=1800, help_text='En segundos.'),
        ),
        migrations.AddField(
            model_name='tasksconfig',
            name='validation_url_check',
            field=models.BooleanField(default=True, verbose_name='Activar validación de URLs con errores de descarga en los reportes'),
        ),
    ]
