# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_datasetpresentrecord_notpresentreportgenerationtask'),
        ('dashboard', '0052_auto_20191024_1010'),
    ]

    operations = [
    ]
