# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_tasksconfig_url_check_timeout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federationtask',
            options={'verbose_name': 'Corrida de federación', 'verbose_name_plural': 'Corridas de federación'},
        ),
        migrations.AlterModelOptions(
            name='harvestingnode',
            options={'verbose_name': 'Nodo federador', 'verbose_name_plural': 'Nodos federadores'},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador de nodos', 'verbose_name_plural': 'Tabla de indicadores de nodos'},
        ),
        migrations.AlterModelOptions(
            name='indicadorfederador',
            options={'verbose_name': 'Indicador de nodos federadores', 'verbose_name_plural': 'Tabla de indicadores de nodos federadores'},
        ),
        migrations.AlterModelOptions(
            name='indicadorred',
            options={'get_latest_by': 'fecha', 'verbose_name': 'Indicador de red', 'verbose_name_plural': 'Tabla de indicadores de red'},
        ),
        migrations.AlterModelOptions(
            name='indicatorsgenerationtask',
            options={'verbose_name': 'Corrida de indicadores', 'verbose_name_plural': 'Corridas de indicadores'},
        ),
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'ordering': ('order',), 'verbose_name': 'Tipo de indicador', 'verbose_name_plural': 'Tipos de indicadores'},
        ),
        migrations.AlterModelOptions(
            name='newlyreportgenerationtask',
            options={'verbose_name': 'Reporte de novedades de datasets', 'verbose_name_plural': 'Reportes de novedades de datasets'},
        ),
        migrations.AlterModelOptions(
            name='notpresentreportgenerationtask',
            options={'verbose_name': 'Reporte de datasets no presentes', 'verbose_name_plural': 'Reportes de datasets no presentes'},
        ),
        migrations.AlterModelOptions(
            name='reportgenerationtask',
            options={'verbose_name': 'Reporte de indicadores', 'verbose_name_plural': 'Reportes de indicadores'},
        ),
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ('order',), 'verbose_name': 'Columna de la tabla de indicadores de red', 'verbose_name_plural': 'Columnas de la tabla de indicadores de red'},
        ),
        migrations.AlterModelOptions(
            name='tasksconfig',
            options={'verbose_name': 'Configuración general', 'verbose_name_plural': 'Configuraciones generales'},
        ),
        migrations.AlterModelOptions(
            name='validationreporttask',
            options={'verbose_name': 'Reporte de validación', 'verbose_name_plural': 'Reportes de validación'},
        ),
    ]
