# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_federation_task_callable_str_django_datajsonar_correction_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksconfig',
            name='federation_url_check',
            field=models.BooleanField(default=False, verbose_name='Activar validación de URLs con errores de descarga en la federación'),
        ),
        migrations.AlterField(
            model_name='tasksconfig',
            name='indicators_url_check',
            field=models.BooleanField(default=False, verbose_name='Activar generación de indicadores de URLs con errores de descarga'),
        ),
        migrations.AlterField(
            model_name='tasksconfig',
            name='validation_url_check',
            field=models.BooleanField(default=False, verbose_name='Activar validación de URLs con errores de descarga en los reportes'),
        ),
    ]
