---

- name: Install firewall
  apt: name=ufw state=present update_cache=yes

- name: Disable firewall
  ufw:
    state: disabled

- name: Disallow incomming
  ufw:
    direction: incoming
    policy: deny

- name: allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: allow application ports
  ufw:
    rule: allow
    to_port: "{{item}}"
  with_items:
    - 22
    - 80
    - 443

- name: Enable firewall
  ufw:
    state: enabled
