---

- name: Install dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git # For pulling the project
    - libpq-dev
    - python-virtualenv
    - python-dev
    - python-pip
    - python-pil
    - libjpeg-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt-dev
    - nginx


# Somehow required by ansible pip module
- name: Install virtualenv
  pip: 
    name: virtualenv
    executable: pip
    virtualenv_python: python2.7
