---

- name: Create the nginx HTTP config file
  template: src=nginx_http_config.j2
            dest={{ nginx_conf_file }}
            mode=0770
            backup=yes
            owner="{{ application_user }}"
            group="www-data"
  when: use_https is not defined

- name: Create the nginx HTTPS config file
  template: src=nginx_https_config.j2
            dest={{ nginx_conf_file }}
            mode=0770
            backup=yes
            owner="{{ application_user }}"
            group="www-data"
  when: use_https is defined

- name: Remove default nginx sites
  file: 
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Add site to sites availables
  file:
    src: "{{ nginx_conf_file }}"
    dest: "/etc/nginx/sites-available/000-default"
    owner: "{{ application_user }}"
    group: "www-data"
    state: link

- name: Enable site
  file:
    src: "/etc/nginx/sites-available/000-default"
    dest: "{{ nginx_enabled_site }}"
    owner: "{{ application_user }}"
    group: "www-data"
    state: link