#! coding: utf-8



DEFAULT_INDICATORS = [
    "pad_compromisos_cant",
    "pad_items_documentados_pct",
    "pad_items_descarga_pct",
    "pad_items_actualizados_pct",
    "pad_items_licencia_pct",
    "datasets_cant",
    "catalogo_ultima_actualizacion_dias",
    "campos_optativos_pct",
    "campos_recomendados_pct",
    "datasets_federados_pct",
    "datasets_actualizados_pct",
    "datasets_meta_ok_pct",
    "distribuciones_formatos_cant",
    "pad_datasets_frecuencia_cant"
]


INDICATORS_INFO = [
    {"indicador_nombre": "catalogos_cant",
     "indicador_nombre_tabla": "Catálogos (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "catalogo_ultima_actualizacion_dias",
     "indicador_nombre_tabla": "Catálogo última actualización (días)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "campos_optativos_pct",
     "indicador_nombre_tabla": "Campos optativos utilizados (%)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "campos_recomendados_pct",
     "indicador_nombre_tabla": "Campos recomendados utilizados (%)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_cant",
     "indicador_nombre_tabla": "Datasets (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_federados_cant",
     "indicador_nombre_tabla": "Datasets federados (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_no_federados_cant",
     "indicador_nombre_tabla": "Datasets no federados (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_federados_pct",
     "indicador_nombre_tabla": "Datasets federados (%)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_actualizados_cant",
     "indicador_nombre_tabla": "Datasets actualizados (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_desactualizados_cant",
     "indicador_nombre_tabla": "Datasets desactualizados (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_actualizados_pct",
     "indicador_nombre_tabla": "Datasets actualizados (%)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_meta_ok_cant",
     "indicador_nombre_tabla": "Datasets cumplen perfil metadatos (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_meta_error_cant",
     "indicador_nombre_tabla": "Datasets no cumplen perfil metadatos (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_meta_ok_pct",
     "indicador_nombre_tabla": "Datasets cumplen perfil metadatos (%)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_frecuencia_cant",
     "indicador_nombre_tabla": "Datasets frecuencias (cant x frecuencia)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "datasets_no_federados",
     "indicador_nombre_tabla": "Datasets no federados (lista)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "distribuciones_cant",
     "indicador_nombre_tabla": "Distribuciones (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "distribuciones_formatos_cant",
     "indicador_nombre_tabla": "Distribuciones formatos (cant x frecuencia)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "pad_jurisdicciones_cant",
     "indicador_nombre_tabla": "Jurisdicciones (cant)",
     "indicador_tipo": "RED"},
    {"indicador_nombre": "pad_compromisos_cant",
     "indicador_nombre_tabla": "Compromisos (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_documentados_cant",
     "indicador_nombre_tabla": "Compromisos documentados (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_no_documentados_cant",
     "indicador_nombre_tabla": "Compromisos no documentados (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_documentados_pct",
     "indicador_nombre_tabla": "Compromisos documentados (%)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_descarga_cant",
     "indicador_nombre_tabla": "Compromisos descargables (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_no_descarga_cant",
     "indicador_nombre_tabla": "Compromisos no descargables (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_descarga_pct",
     "indicador_nombre_tabla": "Compromisos descargables (%)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_actualizados_cant",
     "indicador_nombre_tabla": "Compromisos actualizados (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_desactualizados_cant",
     "indicador_nombre_tabla": "Compromisos desactualizados (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_actualizados_pct",
     "indicador_nombre_tabla": "Compromisos actualizados (%)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_licencia_cant",
     "indicador_nombre_tabla": "Compromisos con licencia (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_sin_licencia_cant",
     "indicador_nombre_tabla": "Compromisos sin licencia (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_items_licencia_pct",
     "indicador_nombre_tabla": "Compromisos con licencia (%)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_datasets_frecuencia_cant",
     "indicador_nombre_tabla": "Datasets frecuencias (cant x frecuencia)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_distribuciones_cant",
     "indicador_nombre_tabla": "Distribuciones (cant)",
     "indicador_tipo": "PAD"},
    {"indicador_nombre": "pad_distributions_formatos_cant",
     "indicador_nombre_tabla": "Distribuciones formatos (cant x frecuencia)",
     "indicador_tipo": "PAD"}
]

