#! coding: utf-8


DEFAULT_INDICATORS = [
    "datasets_cant",
    "catalogo_ultima_actualizacion_dias",
    "campos_optativos_pct",
    "campos_recomendados_pct",
    "datasets_federados_pct",
    "datasets_actualizados_pct",
    "datasets_meta_ok_pct",
    "distribuciones_formatos_cant",
]

INDICATORS_INFO = [
    {"indicador_nombre": "catalogos_cant",
     "indicador_nombre_tabla": "Catálogos (cant)"},
    {"indicador_nombre": "catalogo_ultima_actualizacion_dias",
     "indicador_nombre_tabla": "Catálogo última actualización (días)"},
    {"indicador_nombre": "campos_optativos_pct",
     "indicador_nombre_tabla": "Campos optativos utilizados (%)"},
    {"indicador_nombre": "campos_recomendados_pct",
     "indicador_nombre_tabla": "Campos recomendados utilizados (%)"},
    {"indicador_nombre": "datasets_cant",
     "indicador_nombre_tabla": "Datasets (cant)"},
    {"indicador_nombre": "datasets_federados_cant",
     "indicador_nombre_tabla": "Datasets federados (cant)"},
    {"indicador_nombre": "datasets_no_federados_cant",
     "indicador_nombre_tabla": "Datasets no federados (cant)"},
    {"indicador_nombre": "datasets_federados_pct",
     "indicador_nombre_tabla": "Datasets federados (%)"},
    {"indicador_nombre": "datasets_actualizados_cant",
     "indicador_nombre_tabla": "Datasets actualizados (cant)"},
    {"indicador_nombre": "datasets_desactualizados_cant",
     "indicador_nombre_tabla": "Datasets desactualizados (cant)"},
    {"indicador_nombre": "datasets_actualizados_pct",
     "indicador_nombre_tabla": "Datasets actualizados (%)"},
    {"indicador_nombre": "datasets_meta_ok_cant",
     "indicador_nombre_tabla": "Datasets cumplen perfil metadatos (cant)"},
    {"indicador_nombre": "datasets_meta_error_cant",
     "indicador_nombre_tabla": "Datasets no cumplen perfil metadatos (cant)"},
    {"indicador_nombre": "datasets_meta_ok_pct",
     "indicador_nombre_tabla": "Datasets cumplen perfil metadatos (%)"},
    {"indicador_nombre": "datasets_frecuencia_cant",
     "indicador_nombre_tabla": "Datasets frecuencias (cant x frecuencia)"},
    {"indicador_nombre": "datasets_no_federados",
     "indicador_nombre_tabla": "Datasets no federados (lista)"},
    {"indicador_nombre": "distribuciones_cant",
     "indicador_nombre_tabla": "Distribuciones (cant)"},
    {"indicador_nombre": "distribuciones_formatos_cant",
     "indicador_nombre_tabla": "Distribuciones formatos (cant x frecuencia)"},
]
