---

- name: Create media and static dirs
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}" # Should this be "www-data"?
  with_items:
    - "{{ nginx_media_dir }}"
    - "{{ nginx_static_dir }}"

- name: Get application code
  git:
    accept_hostkey: yes
    repo: "{{ application_clone_url }}"
    dest: "{{ application_repo_dir }}"
    version: "{{ checkout_branch }}"
  tags: quickly

- name: Remove old code
  file:
    path: "{{ application_dir }}"
    state: absent
  tags: quickly

- name: Copy new code
  shell: "cp {{ tempapp }} {{ application_dir }} -r"
  tags: quickly

- name: Remove temp clone folder
  file:
    path: "{{ tempclone }}"
    state: absent
  become_user: "{{ ansible_user }}" # Why?!
  become_method: sudo
  become: yes

- name: Remove temp folder
  file:
    path: "{{ application_temp_dir }}"
    state: absent
