---

- name: Create media and static dirs
  file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}" # Should this be "www-data"?
  with_items:
    - "{{ nginx_media_dir }}"
    - "{{ nginx_static_dir }}"

- name: Get application code
  git:
    accept_hostkey: yes
    repo: "{{ application_clone_url }}"
    dest: "{{ application_dir }}"
    version: "{{ checkout_branch }}"
  tags: quickly
