---

- name: Add python3 repository
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
  become: yes
  become_method: sudo
  become_user: root

- name: Install python 3.6
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  with_items:
    - python3.6
    - python3.6-dev

- name: Check if py2 virtualenv exists
  stat:
    path: "{{ application_virtualenv_dir }}bin/python2"
  register: virtualenv_python2_installed

- name: Remove python 2 virtualenv
  file:
    path: "{{ application_virtualenv_dir }}"
    state: absent
  when: virtualenv_python2_installed.stat.exists == True
  become: yes
  become_user: root

- name: Init virtualenv
  pip: 
    virtualenv: "{{ application_virtualenv_dir }}"
    virtualenv_python: python3.6
    requirements: "{{ application_requirements }}"
  tags: quickly

- name: Ensure django secret key
  script: "django_secret_key.py {{ application_secret_key_file }}"
  args:
    creates: "{{ application_secret_key_file }}"

- name: Get secret key
  slurp:
    src: "{{ application_secret_key_file }}"
  register: secret_key

- name: Set secret key as fact
  set_fact: 
    django_secret_key: "{{ secret_key['content'] | b64decode  }}"

- name: Create the .env file
  template: 
    src: default_env.j2
    dest: "{{ application_env_file }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0770
    backup: yes
    force: no

- name: Add default variables to .env
  blockinfile:
    dest: "{{ application_env_file }}"
    insertbefore: "{{ env_mark }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0770
    content: |
      {% for variable_name, value in django_settings.items() %}
      {{ variable_name }}="{{ value }}"
      {% endfor %}
      DEFAUL_FROM_EMAIL={{ default_from_email }}
      DJANGO_SECRET_KEY="{{ django_secret_key }}"
      {% if sentry_dsn %}
      RAVEN_DSN="{{ sentry_dsn }}"
      SENTRY_ENVIRONMENT="{{ sentry_environment }}"
      {% endif %}
      APP_VERSION={{ checkout_branch }}
      {% if env_type %}
      ENV_TYPE={{ env_type }}
      {% endif %}


- name: Ensure env file
  file:
    src: "{{ application_env_file }}"
    dest: "{{ application_env_file_link }}"
    state: link
  tags: quickly
